server:
    port: 8081
spring:
    datasource:
        database: post
        driver-class-name: com.mysql.cj.jdbc.Driver
        host: localhost
        password: root
        port: 3306
        url: jdbc:mysql://localhost:3306/post?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
        username: root
